name: Generate ascii

on: push

jobs:
    ascii_gen:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List repo file
          run: ls -ltra

        - name: Execute script
          run: ./asciigen.sh