name: Matrix configuration

on:
    workflow_dispatch: 

jobs:
    deploy-on-ubuntu:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, ubuntu-20.4]
            images: [hello-world, alpine]
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo docker details
          run: docker info
        - name: Run image on {{ matrix.os }}
          run: docker run ${{ matrix.images }}

     