name: Multi jobs

on: push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program
          run: sudo apt-get install -y cowsay
        - name: Execute cowsay
          run: cowsay -f dragon "RUN fast ..." >> dragon.txt
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with: 
            name: dragon-file
            path: dragon.txt

    
    test_job2:
        needs: build_job1
        runs-on: ubuntu-latest
        steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with: 
            name: dragon-file
      
        - name: Test if file exists
          run: ls -ltra dragon.txt

    deploy_job3:
        needs: test_job2
        runs-on: ubuntu-latest
        steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with: 
            name: dragon-file
        - name: Read file
          run: cat dragon.txt