name: Exploring workflow filter
on:
  push: 
    branches-ignore: 
        - feature/*  
        - test/**
#    branches: 
    #    - main
    #    - '!feature/*'
  workflow_dispatch: 
  pull_request: 
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo this workflow is executed for event type {{ github.event_type }}